/**
 * Sistema VION de Arquétipos — Jung & Tarot.
 *
 * 12 arquétipos (modelo junguiano / Pearson) + os 4 fundamentais da
 * estrutura psíquica de Jung (Persona, Sombra, Anima/Animus, Self).
 * Cada um corresponde a um Arcano Maior do Tarot e tem uma carta de
 * design original (glifo + numeral), não copiada de nenhum baralho.
 *
 * Conteúdo editável no futuro pelo painel de administração.
 */
export type CartaJung = {
  id: string;
  grupo: '12' | 'fundamental';
  nome: string;
  arcano: string; // nome do Arcano Maior
  numeral: string; // numeral romano do arcano
  glifo: string; // símbolo desenhado na carta
  cor: string; // acento (legível sobre branco)
  essencia: string;
  luz: string;
  sombra: string;
  inconsciente: string;
  dom: string;
  desafio: string;
  integracao: string;
  pergunta: string;
};

export const ARQUETIPOS_12: CartaJung[] = [
  {
    id: 'inocente',
    grupo: '12',
    nome: 'O Inocente',
    arcano: 'O Louco',
    numeral: '0',
    glifo: '☼',
    cor: '#D2A23F',
    essencia: 'A confiança original na vida. O Inocente acredita que o mundo é, no fundo, bom — e parte para a experiência sem couraça.',
    luz: 'Optimismo genuíno, abertura, capacidade de recomeçar. Vê possibilidade onde outros já desistiram.',
    sombra: 'Negação. Para preservar a inocência, recusa ver o que dói — torna-se ingénuo, dependente, evita responsabilidade.',
    inconsciente: 'Por baixo da leveza vive o medo do abandono e do castigo. A inocência é, muitas vezes, uma defesa contra o desamparo vivido cedo.',
    dom: 'Fé. A capacidade de manter o coração aberto depois de saber que a vida também fere.',
    desafio: 'Crescer sem endurecer. Integrar a sombra do mundo sem perder a confiança essencial.',
    integracao: 'A inocência madura não é a que ignora o mal — é a que o conhece e ainda assim escolhe confiar. Chama-se sabedoria do coração.',
    pergunta: 'Onde estou a fingir que não vejo, para não ter de agir?',
  },
  {
    id: 'comum',
    grupo: '12',
    nome: 'O Homem Comum',
    arcano: 'A Roda da Fortuna',
    numeral: 'X',
    glifo: '◉',
    cor: '#8A879E',
    essencia: 'O pertencer. Procura ligação, igualdade e o conforto de não estar à parte. A dignidade do ordinário.',
    luz: 'Empatia, realismo, solidariedade. Liga-se a qualquer pessoa porque não se acha acima de ninguém.',
    sombra: 'Apagamento. Para pertencer, abdica de si — torna-se cínico, mede-se pelos outros, teme destacar-se.',
    inconsciente: 'O medo profundo de ser excluído. Aprendeu que sobressair é perigoso, então esconde o brilho próprio.',
    dom: 'Pertença sem perda de si. Mostrar que se pode ser parte do todo sem desaparecer nele.',
    desafio: 'Aceitar a própria singularidade sem culpa, sem a sentir como traição ao grupo.',
    integracao: 'Quando o Comum honra o que tem de único, descobre que pertencer e ser quem é não se excluem.',
    pergunta: 'O que deixo de fazer só para não me destacar?',
  },
  {
    id: 'heroi',
    grupo: '12',
    nome: 'O Herói',
    arcano: 'A Força',
    numeral: 'VIII',
    glifo: '⚔',
    cor: '#E14242',
    essencia: 'A vontade que enfrenta. Define-se pela coragem de agir perante o difícil e por provar o seu valor através do esforço.',
    luz: 'Disciplina, coragem, competência. Levanta-se quando os outros recuam. Protege.',
    sombra: 'Arrogância e luta perpétua. Sem inimigo, inventa um. Confunde o seu valor com a vitória.',
    inconsciente: 'Por baixo da força mora a ferida de não se sentir suficiente. Luta para não sentir o medo de falhar.',
    dom: 'Coragem ao serviço. A força que protege em vez de dominar.',
    desafio: 'Descobrir que não tem de vencer para valer. Pousar a espada sem se sentir derrotado.',
    integracao: 'O Herói amadurece quando a coragem deixa de ser contra algo e passa a ser por algo. Já não combate — sustenta.',
    pergunta: 'Que batalha continuo a travar só para não sentir o medo por baixo dela?',
  },
  {
    id: 'cuidador',
    grupo: '12',
    nome: 'O Prestador de Cuidados',
    arcano: 'A Temperança',
    numeral: 'XIV',
    glifo: '♥',
    cor: '#0FB67A',
    essencia: 'O amor que serve. Realiza-se ao cuidar, proteger e nutrir o outro. Vê a necessidade antes de a ouvir.',
    luz: 'Compaixão, generosidade, presença. Cria espaços seguros onde os outros florescem.',
    sombra: 'Mártir. Cuida para ser preciso, controla através do dar, esgota-se e cobra em silêncio.',
    inconsciente: 'Aprendeu que só é amado quando é útil. Cuidar do outro é a forma de pedir o cuidado que nunca pediu.',
    dom: 'Cuidar sem se anular. Dar a partir da abundância, não do medo de ser abandonado.',
    desafio: 'Receber. Permitir ser cuidado sem sentir que perde valor.',
    integracao: 'Quando o Cuidador se inclui na lista de quem merece cuidado, o seu amor deixa de ter fatura.',
    pergunta: 'A quem dou tudo, esperando em segredo que adivinhe o que eu preciso?',
  },
  {
    id: 'explorador',
    grupo: '12',
    nome: 'O Explorador',
    arcano: 'O Carro',
    numeral: 'VII',
    glifo: '✧',
    cor: '#7C5CFC',
    essencia: 'A liberdade de procurar. Move-se para encontrar a si mesmo na experiência. O horizonte chama-o sempre.',
    luz: 'Autenticidade, autonomia, sede de verdade. Não se contenta com a vida pré-fabricada.',
    sombra: 'Fuga permanente. Troca de lugar, pessoa e projeto para não ter de chegar — nem se comprometer.',
    inconsciente: 'O movimento esconde o medo do vazio e da intimidade. Se parar, terá de sentir.',
    dom: 'Procura com raiz. Explorar o mundo sem fugir de si.',
    desafio: 'Ficar. Descobrir que a profundidade também é uma fronteira a atravessar.',
    integracao: 'O Explorador inteiro percebe que a maior viagem é para dentro — e essa faz-se parado.',
    pergunta: 'De que é que eu fujo cada vez que sinto vontade de partir?',
  },
  {
    id: 'rebelde',
    grupo: '12',
    nome: 'O Rebelde',
    arcano: 'A Torre',
    numeral: 'XVI',
    glifo: '⚡',
    cor: '#B0822E',
    essencia: 'O que derruba o que já não serve. Questiona regras, expõe a mentira, abre espaço pela rutura.',
    luz: 'Coragem de romper, autenticidade radical, capacidade de libertar o que está preso.',
    sombra: 'Destruição pela destruição. Opõe-se a tudo, queima pontes, confunde revolta com identidade.',
    inconsciente: 'Por baixo da revolta vive uma dor antiga de não ter sido visto ou respeitado. Destruir é gritar.',
    dom: 'Transformação. Derrubar o falso para que o verdadeiro tenha lugar.',
    desafio: 'Construir depois de derrubar. Saber quando a rutura serve e quando só repete a ferida.',
    integracao: 'O Rebelde maduro tornou-se revolucionário: já não destrói para se sentir vivo — transforma para libertar.',
    pergunta: 'O que destruo à minha volta que, no fundo, é raiva por algo antigo?',
  },
  {
    id: 'amante',
    grupo: '12',
    nome: 'O Amante',
    arcano: 'Os Amantes',
    numeral: 'VI',
    glifo: '❧',
    cor: '#E0457F',
    essencia: 'A entrega. Vive pela ligação, pela beleza e pela intensidade do vínculo. Quer fundir-se com o que ama.',
    luz: 'Paixão, devoção, presença sensorial. Faz os outros sentirem-se únicos e desejados.',
    sombra: 'Dependência. Perde-se no outro, teme a solidão, confunde amor com posse ou aprovação.',
    inconsciente: 'O medo de não ser amável. Ama intensamente para garantir que não será deixado.',
    dom: 'Amar mantendo-se inteiro. União sem fusão, entrega sem desaparecimento.',
    desafio: 'Estar só sem se sentir rejeitado. Encontrar dentro o amor que procura fora.',
    integracao: 'O Amante completo sabe que o amor verdadeiro une dois inteiros — não dois meios à procura de se completarem.',
    pergunta: 'O que aceito perder de mim para não perder o outro?',
  },
  {
    id: 'criador',
    grupo: '12',
    nome: 'O Criador',
    arcano: 'A Imperatriz',
    numeral: 'III',
    glifo: '✦',
    cor: '#9B7DF9',
    essencia: 'O impulso de dar forma. Transforma o invisível em obra. Para ele, não criar é uma forma de morrer.',
    luz: 'Imaginação, originalidade, visão. Traz ao mundo o que ainda não existia.',
    sombra: 'Perfeccionismo paralisante. Nunca está bom; identifica-se com a obra e teme o juízo.',
    inconsciente: 'Cria para provar que existe e tem valor. A obra é a tentativa de ser amado por aquilo que faz.',
    dom: 'Criar pelo prazer de criar. Separar o valor próprio do resultado.',
    desafio: 'Mostrar o imperfeito. Libertar a obra antes de ela estar "perfeita".',
    integracao: 'O Criador inteiro percebe que ele não é a obra — é a fonte. E a fonte não precisa de aprovação para correr.',
    pergunta: 'O que não termino por medo de que seja julgado — e eu com ele?',
  },
  {
    id: 'bobo',
    grupo: '12',
    nome: 'O Bobo',
    arcano: 'O Sol',
    numeral: 'XIX',
    glifo: '☀',
    cor: '#E8BE5A',
    essencia: 'A alegria que liberta. Vive o presente, ri do absurdo, dissolve a tensão com leveza. Diz a verdade através do humor.',
    luz: 'Espontaneidade, presença, capacidade de tornar leve o pesado. Cura pelo riso.',
    sombra: 'Evasão. Usa a piada para não sentir; foge da profundidade; nunca leva nada a sério — nem a si.',
    inconsciente: 'O riso esconde tristeza. Aprendeu que ser engraçado garante afecto e desvia a dor.',
    dom: 'Leveza consciente. Rir com a vida sem fugir dela.',
    desafio: 'Deixar-se sentir o que não é engraçado. Estar presente também na dor.',
    integracao: 'O Bobo sábio usa a alegria como verdade, não como fuga. O riso passa a ser presença, não anestesia.',
    pergunta: 'De que sentimento me desvio cada vez que faço uma piada?',
  },
  {
    id: 'sabio',
    grupo: '12',
    nome: 'O Sábio',
    arcano: 'O Eremita',
    numeral: 'IX',
    glifo: '✶',
    cor: '#0089A8',
    essencia: 'A busca da verdade. Quer compreender. Confia no conhecimento e na clareza como caminho para a liberdade.',
    luz: 'Discernimento, objetividade, sabedoria. Vê o padrão por baixo do ruído.',
    sombra: 'Frieza e paralisia. Analisa para não sentir; adia a vida à espera de "saber o suficiente"; despreza quem não pensa como ele.',
    inconsciente: 'Por baixo do intelecto, o medo de errar e de se entregar. Saber é a forma de controlar.',
    dom: 'Sabedoria encarnada. Conhecimento que serve a vida, não que a substitui.',
    desafio: 'Descer da mente ao corpo. Viver o que compreende.',
    integracao: 'O Sábio completo une mente e coração: já não acumula saber — torna-se presença que esclarece pela escuta.',
    pergunta: 'Que decisão adio à espera de ter a certeza que nunca vem?',
  },
  {
    id: 'mago',
    grupo: '12',
    nome: 'O Mago',
    arcano: 'O Mago',
    numeral: 'I',
    glifo: '✺',
    cor: '#6E4FDB',
    essencia: 'O poder de transformar. Liga mundos — o interno e o externo, o visível e o invisível. Sabe que a consciência molda a realidade.',
    luz: 'Visão, intenção, capacidade de manifestar. Catalisa transformação em si e nos outros.',
    sombra: 'Manipulação. Usa o poder para controlar, seduzir ou dominar. Ilude-se com a própria grandeza.',
    inconsciente: 'O medo de ser impotente. O poder compensa uma antiga experiência de não ter controlo nenhum.',
    dom: 'Poder ao serviço. Transformar com integridade, sem manipular.',
    desafio: 'Render o controlo. Distinguir manifestar de forçar.',
    integracao: 'O Mago inteiro percebe que o verdadeiro poder não dobra a realidade — alinha-se com ela. Torna-se canal, não dono.',
    pergunta: 'Onde estou a forçar, quando devia estar a alinhar?',
  },
  {
    id: 'governante',
    grupo: '12',
    nome: 'O Governante',
    arcano: 'O Imperador',
    numeral: 'IV',
    glifo: '♛',
    cor: '#B0822E',
    essencia: 'A ordem que sustenta. Cria estrutura, assume responsabilidade, protege o que é seu. Quer um mundo estável e justo.',
    luz: 'Liderança, responsabilidade, capacidade de criar ordem do caos. Faz acontecer.',
    sombra: 'Tirania e rigidez. Controla por medo de perder; confunde poder com valor; não tolera ser questionado.',
    inconsciente: 'Por baixo do controlo vive o caos que teme — muitas vezes uma infância sem segurança. Mandar é não voltar a sentir-se impotente.',
    dom: 'Autoridade que serve. Liderar a partir da responsabilidade, não do medo.',
    desafio: 'Soltar o controlo. Confiar e delegar sem sentir que se desmorona.',
    integracao: 'O Governante maduro torna-se servidor: governa para o bem do todo, não para defender a coroa.',
    pergunta: 'Que controlo seguro com força, por medo do que aconteceria se o largasse?',
  },
];

export const FUNDAMENTAIS_4: CartaJung[] = [
  {
    id: 'persona',
    grupo: 'fundamental',
    nome: 'A Persona',
    arcano: 'O Hierofante',
    numeral: 'V',
    glifo: '◑',
    cor: '#8A879E',
    essencia: 'A máscara social. O rosto que mostramos ao mundo para sermos aceites — o papel, a imagem, o "eu apresentável".',
    luz: 'Permite viver em sociedade, adaptar-se, proteger a intimidade. Saudável quando sabemos que é uma máscara.',
    sombra: 'Identificação total. Quando confundimos quem somos com o papel, perdemos o contacto com o verdadeiro self e vivemos em representação.',
    inconsciente: 'A persona forma-se cedo, a partir do que foi premiado e do que foi punido. Esconde o que aprendemos a não mostrar.',
    dom: 'Adaptação consciente. Usar a máscara sem ser usado por ela.',
    desafio: 'Reconhecer onde acaba o papel e começa a pessoa.',
    integracao: 'Quando sabemos que a persona é roupa, não pele, podemos vesti-la e despi-la livremente — sem mentir a nós mesmos.',
    pergunta: 'Quem sou eu quando ninguém está a ver?',
  },
  {
    id: 'sombra',
    grupo: 'fundamental',
    nome: 'A Sombra',
    arcano: 'O Diabo',
    numeral: 'XV',
    glifo: '☾',
    cor: '#1B1830',
    essencia: 'Tudo o que rejeitámos de nós e empurrámos para o escuro: os impulsos, desejos e traços que julgámos inaceitáveis.',
    luz: 'A sombra contém ouro. Nela vive energia vital, criatividade e poder que negámos. Integrá-la devolve inteireza.',
    sombra: 'Projeção. O que não vemos em nós, vemos (e atacamos) nos outros. A sombra não integrada governa-nos sem sabermos.',
    inconsciente: 'É o próprio inconsciente pessoal: o depósito de tudo o que a persona excluiu para ser aceite.',
    dom: 'Inteireza. Recuperar a energia presa no que foi negado.',
    desafio: 'Olhar para o que nos envergonha sem fugir nem nos identificar com isso.',
    integracao: '"Não nos tornamos iluminados imaginando luz, mas tornando consciente a escuridão" (Jung). Integrar a sombra é o ato central do crescimento.',
    pergunta: 'O que mais me irrita nos outros — e onde é que isso vive em mim?',
  },
  {
    id: 'anima',
    grupo: 'fundamental',
    nome: 'Anima / Animus',
    arcano: 'A Sacerdotisa',
    numeral: 'II',
    glifo: '☽',
    cor: '#7C5CFC',
    essencia: 'A alma contrassexual: o feminino interior no homem (anima) e o masculino interior na mulher (animus). A ponte para o inconsciente.',
    luz: 'Quando integrada, traz equilíbrio entre razão e sentir, ação e receção. Inspira, liga ao criativo e ao profundo.',
    sombra: 'Projetada, faz-nos idealizar ou culpar o outro pelo que não desenvolvemos em nós. Gera relações de fascínio e desilusão.',
    inconsciente: 'É a figura que aparece nos sonhos como o "outro" — guia ou sedutor — apontando o que falta integrar.',
    dom: 'Completude interior. Casar dentro de si os opostos que se procuram fora.',
    desafio: 'Parar de exigir ao outro que seja a metade que nos falta.',
    integracao: 'Integrar a anima/animus é deixar de procurar fora a alma que se desenvolve dentro. O par exterior torna-se encontro, não muleta.',
    pergunta: 'O que espero que o outro me dê, que afinal me cabe a mim desenvolver?',
  },
  {
    id: 'self',
    grupo: 'fundamental',
    nome: 'O Self',
    arcano: 'O Mundo',
    numeral: 'XXI',
    glifo: '✸',
    cor: '#B0822E',
    essencia: 'O centro e a totalidade da psique. Não o ego (o "eu" consciente), mas o todo que integra consciente e inconsciente — a meta da individuação.',
    luz: 'Sentido, inteireza, ligação a algo maior. Quando o ego serve o Self, a vida ganha direção e profundidade.',
    sombra: 'Inflação. O ego confunde-se com o Self e julga-se especial, iluminado, acima — ou, no oposto, sente-se esmagado pelo divino.',
    inconsciente: 'Manifesta-se em símbolos de totalidade: o círculo, a mandala, o quaternário. É o organizador silencioso de toda a psique.',
    dom: 'Individuação. Tornar-se quem realmente se é, integrando todas as partes.',
    desafio: 'Deixar o ego servir o todo, sem se inflar nem se anular.',
    integracao: 'A individuação não é tornar-se perfeito — é tornar-se completo. O Self é a bússola; o caminho é de uma vida inteira.',
    pergunta: 'Se eu já não tivesse nada a provar, que vida escolheria viver?',
  },
];

export const TODAS_CARTAS: CartaJung[] = [...ARQUETIPOS_12, ...FUNDAMENTAIS_4];

export const getCartaJung = (id: string): CartaJung | undefined =>
  TODAS_CARTAS.find((c) => c.id === id);
