export type Opcao = { texto: string; hz: number };
export type Pergunta = { id: number; bloco: 1 | 2; scene: string; opcoes: Opcao[] };

export const PERGUNTAS: Pergunta[] = [
  {
    id: 1,
    bloco: 1,
    scene: 'Acordas e o primeiro pensamento do dia é...',
    opcoes: [
      { texto: 'Já estou atrasado — o dia vai correr mal', hz: 100 },
      { texto: 'Mais um dia igual', hz: 50 },
      { texto: 'O que posso fazer de bom hoje?', hz: 310 },
      { texto: 'Gratidão por estar aqui', hz: 540 },
      { texto: 'Ansiedade sobre o que vem aí', hz: 125 },
    ],
  },
  {
    id: 2,
    bloco: 1,
    scene: 'Alguém te critica em público.',
    opcoes: [
      { texto: 'Humilhação. Quero desaparecer', hz: 20 },
      { texto: 'Raiva imediata', hz: 150 },
      { texto: 'Ouço — pode ter algo útil', hz: 200 },
      { texto: 'Curiosidade genuína', hz: 400 },
      { texto: 'Não me define. Sigo', hz: 350 },
    ],
  },
  {
    id: 3,
    bloco: 1,
    scene: 'Vês uma pessoa com muito sucesso na tua área.',
    opcoes: [
      { texto: 'Inveja. Por que não eu?', hz: 125 },
      { texto: 'Irritação — deve ter tido sorte', hz: 150 },
      { texto: 'Inspiração — se ela conseguiu, eu também posso', hz: 200 },
      { texto: 'Alegria genuína pelo sucesso dela', hz: 500 },
      { texto: 'Indiferença — foco no meu caminho', hz: 250 },
    ],
  },
  {
    id: 4,
    bloco: 1,
    scene: 'Um projecto em que acreditavas falhou completamente.',
    opcoes: [
      { texto: 'Sou um fracasso', hz: 30 },
      { texto: 'Raiva de mim e das circunstâncias', hz: 150 },
      { texto: 'O que posso aprender aqui?', hz: 250 },
      { texto: 'Fazia parte do caminho', hz: 350 },
      { texto: 'Já estou a pensar no próximo', hz: 200 },
    ],
  },
  {
    id: 5,
    bloco: 1,
    scene: 'Estás sozinho(a) sem telemóvel por 3 horas.',
    opcoes: [
      { texto: 'Ansiedade — o silêncio assusta', hz: 100 },
      { texto: 'Inquietação — preciso de estímulo', hz: 125 },
      { texto: 'Conforto — sou boa companhia para mim', hz: 350 },
      { texto: 'Riqueza interior — é onde me encontro', hz: 540 },
      { texto: 'Neutro — é apenas espaço', hz: 250 },
    ],
  },
  {
    id: 6,
    bloco: 1,
    scene: 'Pensas no futuro — nos próximos 5 anos.',
    opcoes: [
      { texto: 'Medo. Muito pode correr mal', hz: 100 },
      { texto: 'Ansiedade misturada com esperança', hz: 125 },
      { texto: 'Confiança calma — não sei o que vem, mas estou bem', hz: 350 },
      { texto: 'Entusiasmo — há muito por criar', hz: 310 },
      { texto: 'Paz. O futuro é o presente a desdobrar-se', hz: 600 },
    ],
  },
  {
    id: 7,
    bloco: 1,
    scene: 'Alguém próximo conquista algo que desejas para ti.',
    opcoes: [
      { texto: 'Inveja. Fico perturbado(a) por dentro', hz: 125 },
      { texto: 'Misto de alegria e dor', hz: 175 },
      { texto: 'Alegria genuína — o sucesso dele não diminui o meu', hz: 500 },
      { texto: 'Indiferença', hz: 250 },
      { texto: 'Inspiração', hz: 200 },
    ],
  },
  {
    id: 8,
    bloco: 1,
    scene: 'Vês uma pessoa sem abrigo na rua.',
    opcoes: [
      { texto: 'Desconforto — desvio o olhar', hz: 75 },
      { texto: 'Pena, mas sigo em frente', hz: 150 },
      { texto: 'Compaixão — pergunto-me o que a trouxe aqui', hz: 500 },
      { texto: 'Faço algo concreto', hz: 400 },
      { texto: 'Amor universal — vejo a humanidade', hz: 540 },
    ],
  },
  {
    id: 9,
    bloco: 1,
    scene: 'Estás a fazer algo que amas — trabalho criativo, natureza, música.',
    opcoes: [
      { texto: 'Raramente acontece — a vida não dá espaço', hz: 50 },
      { texto: 'Prazer com culpa — devia estar a ser produtivo(a)', hz: 30 },
      { texto: 'Fluxo — o tempo para, estou completamente presente', hz: 540 },
      { texto: 'Satisfação tranquila e profunda', hz: 350 },
      { texto: 'Alegria pura', hz: 500 },
    ],
  },
  {
    id: 10,
    bloco: 1,
    scene: 'Alguém te pede ajuda numa altura em que também precisas de ajuda.',
    opcoes: [
      { texto: 'Ajudo e guardo o ressentimento', hz: 125 },
      { texto: 'Explico que não estou em condições agora', hz: 200 },
      { texto: 'Ajudo — isso de certa forma também me ajuda', hz: 500 },
      { texto: 'Avalio e faço o que consigo sem me perder', hz: 310 },
      { texto: 'Ajudo incondicionalmente', hz: 540 },
    ],
  },
  {
    id: 11,
    bloco: 1,
    scene: 'Pensas na tua própria mortalidade.',
    opcoes: [
      { texto: 'Terror. Evito pensar nisso', hz: 100 },
      { texto: 'Tristeza e alguma aceitação', hz: 250 },
      { texto: 'Paz. A morte faz parte', hz: 600 },
      { texto: 'Urgência — quero viver plenamente enquanto posso', hz: 310 },
      { texto: 'É apenas uma transição. Não temo', hz: 700 },
    ],
  },
  {
    id: 12,
    bloco: 1,
    scene: 'No fim de um dia comum, sozinho(a) com os teus pensamentos.',
    opcoes: [
      { texto: 'Exaustão e vazio', hz: 50 },
      { texto: 'Preocupação com o amanhã', hz: 100 },
      { texto: 'Satisfação tranquila com o que foi', hz: 350 },
      { texto: 'Gratidão genuína por existir', hz: 540 },
      { texto: 'Uma paz que não precisa de explicação', hz: 600 },
    ],
  },
  {
    id: 13,
    bloco: 2,
    scene: 'No fundo, acreditas que mereces coisas boas?',
    opcoes: [
      { texto: 'Não. Tenho de merecer — e raramente mereço', hz: 30 },
      { texto: 'Às vezes, quando me porto bem', hz: 175 },
      { texto: 'Sim, com esforço constante', hz: 200 },
      { texto: 'Sim, simplesmente por existir', hz: 500 },
      { texto: 'É uma pergunta que nunca me fiz', hz: 250 },
    ],
  },
  {
    id: 14,
    bloco: 2,
    scene: 'Quando algo corre muito bem na tua vida...',
    opcoes: [
      { texto: 'Espero que a má sorte apareça logo', hz: 100 },
      { texto: 'Tenho medo de perder', hz: 125 },
      { texto: 'Aproveito com gratidão', hz: 350 },
      { texto: 'É natural — estou alinhado(a)', hz: 500 },
      { texto: 'Fico surpreendido(a) — não esperava', hz: 175 },
    ],
  },
  {
    id: 15,
    bloco: 2,
    scene: 'A tua relação com o dinheiro é...',
    opcoes: [
      { texto: 'Ansiedade constante — nunca é suficiente', hz: 100 },
      { texto: 'Culpa quando gasto em mim', hz: 30 },
      { texto: 'Ferramenta — uso com consciência', hz: 350 },
      { texto: 'Fluxo — entra e sai naturalmente', hz: 500 },
      { texto: 'Tensão — quero mais mas sinto que não mereço', hz: 125 },
    ],
  },
  {
    id: 16,
    bloco: 2,
    scene: 'Como te sentes no teu corpo?',
    opcoes: [
      { texto: 'Desconforto — não me sinto em casa aqui', hz: 50 },
      { texto: 'Indiferença — ignoro o que sinto', hz: 75 },
      { texto: 'Respeito — cuido dele conscientemente', hz: 310 },
      { texto: 'Gratidão — é o meu templo', hz: 500 },
      { texto: 'Tensão crónica que não consigo libertar', hz: 100 },
    ],
  },
  {
    id: 17,
    bloco: 2,
    scene: 'Quando alguém te ama genuinamente...',
    opcoes: [
      { texto: 'Desconfiança — o que quer de mim?', hz: 100 },
      { texto: 'Não acredito que seja real', hz: 30 },
      { texto: 'Recebo com alguma dificuldade', hz: 175 },
      { texto: 'Recebo com abertura e gratidão', hz: 350 },
      { texto: 'Correspondo naturalmente', hz: 500 },
    ],
  },
  {
    id: 18,
    bloco: 2,
    scene: 'O teu diálogo interno predominante é...',
    opcoes: [
      { texto: 'Crítica constante — nunca é suficiente', hz: 30 },
      { texto: 'Comparação com os outros', hz: 125 },
      { texto: 'Neutro — observo sem julgar', hz: 250 },
      { texto: 'Encorajamento — sou meu melhor aliado(a)', hz: 400 },
      { texto: 'Silêncio interior com clareza', hz: 600 },
    ],
  },
  {
    id: 19,
    bloco: 2,
    scene: 'Quando sentes raiva, o que fazes?',
    opcoes: [
      { texto: 'Expludo para fora', hz: 150 },
      { texto: 'Engulo e guardo dentro', hz: 75 },
      { texto: 'Ignoro e finjo que não existe', hz: 50 },
      { texto: 'Reconheço, processo e liberto', hz: 310 },
      { texto: 'Uso como informação — o que me está a dizer?', hz: 400 },
    ],
  },
  {
    id: 20,
    bloco: 2,
    scene: 'A tua relação com o passado é...',
    opcoes: [
      { texto: 'Mágoa que ainda não curei', hz: 75 },
      { texto: 'Culpa pelo que fiz ou não fiz', hz: 30 },
      { texto: 'Nostalgia — era melhor antes', hz: 125 },
      { texto: 'Gratidão — formou quem sou', hz: 350 },
      { texto: 'Libertação — já não me define', hz: 400 },
    ],
  },
  {
    id: 21,
    bloco: 2,
    scene: 'Quando imaginas a melhor versão de ti mesmo(a)...',
    opcoes: [
      { texto: 'Parece impossível ou muito distante', hz: 50 },
      { texto: 'Sinto medo de não chegar lá', hz: 100 },
      { texto: 'Vejo-a como possível com esforço', hz: 200 },
      { texto: 'Sinto que já estou a tornar-me ela', hz: 400 },
      { texto: 'Já sou essa versão — estou em expansão', hz: 540 },
    ],
  },
  {
    id: 22,
    bloco: 2,
    scene: 'O teu propósito de vida é...',
    opcoes: [
      { texto: 'Não sei. Essa pergunta assusta-me', hz: 100 },
      { texto: 'Sobreviver e manter o que tenho', hz: 125 },
      { texto: 'Crescer e realizar-me', hz: 310 },
      { texto: 'Contribuir para algo maior que eu', hz: 500 },
      { texto: 'Ser canal de amor e consciência', hz: 600 },
    ],
  },
  {
    id: 23,
    bloco: 2,
    scene: 'Quando tens momentos de silêncio e quietude...',
    opcoes: [
      { texto: 'Nunca faço — não consigo parar', hz: 125 },
      { texto: 'Tento mas a mente não para', hz: 150 },
      { texto: 'Consigo algum silêncio com esforço', hz: 250 },
      { texto: 'O silêncio vem naturalmente', hz: 400 },
      { texto: 'Sou o silêncio — observo os pensamentos', hz: 600 },
    ],
  },
  {
    id: 24,
    bloco: 2,
    scene: 'A tua crença mais profunda sobre a vida é...',
    opcoes: [
      { texto: 'A vida é sofrimento e luta', hz: 50 },
      { texto: 'A vida é imprevisível e assustadora', hz: 100 },
      { texto: 'A vida é uma oportunidade de crescer', hz: 310 },
      { texto: 'A vida é uma dádiva a celebrar', hz: 500 },
      { texto: 'A vida é consciência a experienciar-se a si mesma', hz: 700 },
    ],
  },
];
